[pytest]
addopts = --cov=parse --cov-report=term-missing --cov-append --cov-branch --doctest-modules --doctest-glob=README.rst --ignore=tests/test_typing.py

# For Python 2.7 / pytest-4.6:
collect_ignore = ["tests/test_typing.py"]